name: CC Tools Dev
version: "1.0.17"
slug: cc_tools
description: Automatiza tareas de Creality Cloud desde Home Assistant.
url: https://github.com/micasadomotica/CC-Tools-HA
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
webui: "http://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Interfaz web de CC Tools
options:
  timezone: Europe/Madrid
schema:
  timezone: str
